language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script: "npm test"
before_script:
  - "./test/hosts.sh"
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq graphicsmagick
notifications:
 irc:
   channels:
     - "chat.freenode.net#pump.io"
   on_success: change
   on_failure: change
